# Generated by Django 4.2.4 on 2023-11-20 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="icon",
            field=models.ImageField(
                default="vaalser.png",
                height_field=250,
                upload_to="images/",
                width_field=250,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="url",
            field=models.URLField(default="https://nomenetomen.de"),
        ),
        migrations.AddField(
            model_name="blog",
            name="votes_total",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
