# Generated by Django 4.2.4 on 2023-11-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
    ]
