# Generated by Django 4.2.4 on 2023-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blog_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="icon",
        ),
        migrations.AddField(
            model_name="blog",
            name="author_icon",
            field=models.ImageField(default="vaalser.png", upload_to="images/"),
        ),
    ]
