# Generated by Django 4.2.4 on 2023-10-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="abstract",
            field=models.CharField(default="", max_length=255),
        ),
    ]
